<a href="https://colab.research.google.com/github/ddr4x/LinAlgDS/blob/main/audio_with_numpy_unsolved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of numpy... and music

numpy ('num-pie' not 'num-pee'!) is a python library for **vector** (matrix/tensor) computations modelled after matlab.

> Handling vectors is one of the two good things about matlab.

They work similarly to lists (len, indexing etc), but they really behave like mathematical vectors in terms of (*, +)

We'll look at:
- np.pi
- adding an np.array by a scalar, multiplying by another vector
- np.concatenate
- np.linspace, np.zeros, np.ones
- np.sin, np.cos, np.sqrt, np.log ...

> We won't be using the standard python math library **at all**. It doesn't work well with numpy...

In later lectures we will learn many functions, and will start using higher-dimensional arrays. For now we stick to 1-dimensional (flat) vectors.



## An application (second part)

In this course we'll often represent data as vectors.

> We've seen in with the text data and term-vectors

Today we'll represent and manipulate sound/music data as vectors (stored as np.arrays). In particular, we will try to **compose music** :)



# Importing numpy and accessing its contents

In [1]:
import numpy as np # we import the numpy package and give it an alias (name)

In [2]:
np.pi, np.cos(0)

(3.141592653589793, 1.0)

# Basics of np.arrays

Sometimes you will create np.arrays from lists/tuples

In [3]:
u = np.array([1.,2,3,10]) # if you want floats, >= element should be a float!
v = np.array([100.,200,300,500])

print(u+v) # let's try some more! what does u*v do? what else can we do?

[101. 202. 303. 510.]


In [4]:
len(u)

4

In [5]:
u[0], u[-1], u[:2], u[-2:] # indexing/slicing is similar to lists!

(1.0, 10.0, array([1., 2.]), array([ 3., 10.]))

In [6]:
u[:2] = 0 # we can also change a sub-array, useful!

In [7]:
list(u) # if absolutely needed, you can turn an np.array into a regular list (or tuple)

[0.0, 0.0, 3.0, 10.0]

## Arrays of ones and zeros

It's often useful to have a large array of zeros or ones, so that you can do something to them.

In [8]:
np.ones(10), np.zeros(10)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

## np.linspace (super useful)

Used to create $n$ numbers evenly spaced between $a$ and $b$ (inclusive).

> It also works if $a$ and $b$ are np.arrays/vectors.

In [9]:
xs = np.linspace(0,np.pi, 10**6)
print(xs, len(xs))

[0.00000000e+00 3.14159580e-06 6.28319159e-06 ... 3.14158637e+00
 3.14158951e+00 3.14159265e+00] 1000000


## Applying functions on np.arrays

If we apply a mathematical function $f : \mathbb{R} \to \mathbb{R}$ to a vector in $\mathbb{R}^n$, numpy will automatically compute $f$ on each component of this vector.

> This is *much* more efficient than doing a list comprehension!

In [10]:
np.sin(xs)

array([0.00000000e+00, 3.14159580e-06, 6.28319159e-06, ...,
       6.28319159e-06, 3.14159580e-06, 1.22464680e-16])

## Extra (timings!)

> We can use %timeit to time an expression

Note that the above is:
- ~80x faster than using np.sin in list comprehension (np.sin is really optimized for working on np.arrays not single numbers!)
- ~10x faster than using math.sin in list comprehension


In [ ]:
%timeit np.sin(xs)

In [ ]:
%timeit [np.sin(x) for x in xs]

In [ ]:
import math

In [ ]:
%timeit [math.sin(x) for x in xs]

# Concatenating

We can  put one vector after another using the np.concatenate function.

> Note that the function takes a tuple of np.arrays

In [ ]:
c = np.concatenate((u,v,u))
print(c)

# Making noise

An np.array representing a sine wave can be interpreted as sound. You can actually play it below.

- Try to generate some tones, add them together, multiply by a scalar etc.
- You can also use np.concatenate many basic tones to create longer vectors representing sounds
- You can also mix these longer sounds etc.

This could help: https://pages.mtu.edu/~suits/notefreqs.html

> Tip: the sound playback normalizes the maximum volume in a given sound. So even if you make the entire sound, say, twice as loud, you'll get the same playback volume. But if you make part of the sound louder, you will hear it louder.

In [25]:
# Don't mind the things below too much, you'll just be using the functions
from IPython.display import Audio

TIMESTEPS_PER_SECOND = 20_000

def make_tone(freq, duration_in_sec = 1.):
  ts = np.linspace(0, np.pi*2, int(TIMESTEPS_PER_SECOND * duration_in_sec))
  return np.sin(ts * freq)

def play_sound(sound : np.array):
  return Audio(sound, rate=TIMESTEPS_PER_SECOND)

In [26]:
c_4_freq = 261.63	 # some C sound

c_sound = make_tone(c_4_freq)

# this must be the last thing in a cell you do, for some reason
play_sound(c_sound)

# Task 1

Implement a function which generates a whole range of tones. Play them in all order. Do they sound okay?

> You can return it as a tuple/array of np.arrays

Ideally create one *octave* of sounds starting from $C_4$ to $C_5$ (including the semitones like $C^{\#}_4$). You may then select only the full tones, because they may be easier to work with.

> If you don't know what that means, just try out various frequencies and create sounds from them.

> BTW. Have you ever wondered about the name of the programming language $C^{\#}$?

In [36]:
def generate_tones(from_freq, n):
  q= 2**(1/12)
  return [make_tone(from_freq * q**k) for k in range(13)]

In [37]:
# play them
tones = generate_tones(c_4_freq, None)
play_sound(np.concatenate(tones))


In [23]:
#geom space
sounds = []
s = np.linspace(180, 360, 8)
for i in range(8):
  sounds.append(s[i])
print(sounds)

[180.0, 205.71428571428572, 231.42857142857144, 257.1428571428571, 282.8571428571429, 308.57142857142856, 334.2857142857143, 360.0]


# Task 2

Take a couple of sounds generated in Task 1 and see what happens if you
add two sounds, multiply a sound by a number, concatenate two sounds etc.

Formulate an answer for what each of these mathematical operations does to the sound.

> Tip: remember the tip above aboud the volume/loundness of playback.

# Mildly optional Task 2.5

You may have noticed the annoying 'click' at the end of each tone we generate with make_tone. Can you fix this?

Implement a function which gets rid of this. Use it in the next tasks.

> It doesn't have to be sophisticated, but it's best if it keeps the length of the np.array the same.

In [ ]:
def fade_out(tone):
  pass

In [ ]:
# for example:
fade_out(c_sound)
play_sound(c_sound) # should sound nice

# Task 3

Using tasks 1 and 2, create a short song by combining individual tones.

It can be e.g. some childrens' song popular in whatever country you're from.

> Tip you can also add pauses/silence



In [ ]:
# here is one supposed classic to get you started:
length_in_sec = 273
concert = np.zeros(length_in_sec * TIMESTEPS_PER_SECOND)
concert[0] = 1
play_sound(concert)

# More ambitious Extra Task 4

Each of your tones had a constant frequency. One can also create music by changing the frequency of the sound (almost) continously. https://en.wikipedia.org/wiki/Musical_saw is one example which comes to mind.

Try to generate some sounds based on this idea.

> This is worth 1 activity point for the most most elegant and/or nice-sounding solutions (if any).